### ISSUE TITLE
apply fails if the previous helm install command fails 

### ISSUE THREAD

**Issue by ashinohara** [djhaskin987/terraform-provider-helmcmd#7]
Helm has a bug in `helm upgrade --install` that causes subsequent runs to fail if the first run fails: https://github.com/helm/helm/issues/3353

I believe that in the plugin, the following path could be taken so that each run of apply is idempotent (suggested [here](https://github.com/helm/helm/issues/3353#issuecomment-385222233)):

helm upgrade --install
    

+ if FAIL then
    - if revision=1
        - then helm delete --purge
    - else helm rollback

**Comment by djha-skin** [comment]
Ah yes, the "first failure" helm problem. I've thought a bit about this.

Firstly, I don't want the provider to roll back a release that it had just created during the same run of `terraform apply`. That would disagree with Terraform's philosophy not to roll back in the presence of errors. I also don't want to implement a feature that I feel would cause instability in the future and make needless room for bugs to crop up. 

I _would_, in theory, be okay with the provider bulldozing over a failed first deploy using the logic you have written above when `terraform apply` is called the second time. I wouldn't want this to be the default behavior, but I'd be okay with implementing this under an option in the provider (something like `delete_first_failure`). However, because of the way Terraform works, there is no way to do this cleanly.

Terraform knows about four operations: create, read, update, and delete. I could perhaps implement `helm delete --purge` of first-failure operations in the "update" section of the code, but terraform may call the "read" function before it does any updates. This case occurs when the `-refresh=true` option is given to `terraform apply`, for example. As coded (and I believe rightly so), when terraform calls "read" on this provider the plugin grabs information from helm, detects that the deployment is in a state of failure, and returns an error to Terraform. Therefore, in order to get an update (`terraform apply`) to blow away or roll back any prior releases with `Revision` of 1, the provider would have to "lie" to Terraform and tell it that all is well so that the update can happen, which is just asking for trouble. 

I also want to acknowledge this problem, though. I've dealt with it myself, and it is terribly annoying. I just don't see a good way of pushing the logic to deal with that failure state "down" into a terraform provider without violating "trust" with Terraform, and not violating Terraform's assumptions surrounding how providers should behave is one of the two main reasons for this provider's existence.

**Comment by ashinohara** [comment]
Keeping it in line with terraform philosophy makes sense.  Do you know if there is any precedent for automatically `taint`-ing resources if they fail?  Another course of action could be to `taint` the helm release, which I believe should then call for the deletion and recreation of the resource on the next `apply`.  This could be done manually as well, but the experience would be better if it happened automatically.

**Comment by djha-skin** [comment]
I apologize for the late response.

Terraform really doesn't like rolling back in the face of errors. To fix this problem in any way would be to roll back in the face of an error. 

I feel like the best place to solve this problem isn't in a terraform plugin, nor perhaps in a helm patch, but in the script which you write that runs terraform.

I like the approach of being more terraform-y like what you're doing. I would like to keep trying with you to figure this out so that we can eliminate this pain point.

That said, I do not believe tainting is an option available to us in this fight. [To quote the docs](https://www.terraform.io/docs/commands/taint.html):

> Forcing the recreation of a resource is useful when you want a certain side effect of recreation that is not visible in the attributes of a resource. For example: re-running provisioners will cause the node to be different or rebooting the machine from a base image will cause new startup scripts to run.
> 
> Note that tainting a resource for recreation may affect resources that depend on the newly tainted resource. For example, a DNS resource that uses the IP address of a server may need to be modified to reflect the potentially new IP address of a tainted server. The plan command will show this if this is the case.

The first paragraph makes it clear that tainting exists to clean up configuration drift by re-running provisioners in a cleanly-created environment. The second paragraph makes clear that tainting should not be done lightly, as it may cause updates in other infrastructure. Therefore, tainting should only be done manually.

This seems to be how it was designed; for example, in `helper/schema`, the library that terraform provides to interact with Terraform from the plugin, there is no way to mark a resource as tainted or even to react to a tainted resource or know that it is tainted.
